Second branch testing workflow with updations

diff --git a/.github/workflows/Test-kitctl.yml b/.github/workflows/Test-kitctl.yml
--- a/.github/workflows/Test-kitctl.yml
+++ b/.github/workflows/Test-kitctl.yml
@@ -13,31 +13,22 @@ jobs:
     name: kitctl-Test
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-    - uses: actions/cache@v2
-      with:
-        path: |
-          ~/.cache/go-build
-          ~/go/pkg/mod
-          ~/go/bin/
-        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-        restore-keys: |
-          ${{ runner.os }}-go-
-    - uses: actions/setup-go@v2
-      with:
-        go-version: '1.17.1'
-    - name: configure aws credentials
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-          role-to-assume: arn:aws:iam::953421922360:role/kit-Github-workflow
-          role-session-name: githubworkflowsession
-          aws-region: us-west-2
+    - uses: ./.github/actions/Go-setup/action
     - name: Builds the KIT CLI ,Provisions the Kit Environment and deletes it
       run: |
         cd /home/runner/work/kubernetes-iteration-toolkit/kubernetes-iteration-toolkit/substrate/cmd/kitctl
         go build -v .
-        RANDOM_SUFFIX=$(openssl rand -hex 5)
-        ./kitctl bootstrap kit-github-${RANDOM_SUFFIX}
-        export KUBECONFIG=/home/runner/.kit/env/kit-github-${RANDOM_SUFFIX}/etc/kubernetes/admin.conf
-        ./kitctl delete kit-github-${RANDOM_SUFFIX}
+        ./kitctl bootstrap kit-github-${{ github.run_id }}
+        export KUBECONFIG=/home/runner/.kit/env/kit-github-${{ github.run_id }}/etc/kubernetes/admin.conf
+        kubectl get pods -A
+        for i in {1..5}; do
+        if ./kitctl delete kit-github-${{ github.run_id }}; then
+          break
+        fi
+        sleep 20
+        done
+        if [ $i -eq 5 ]; then
+          echo "Failed to delete the kit-github-${{ github.run_id }} environment after 5 attempts. Please manually delete the environment."
+          exit 1
+        fi
       working-directory: substrate
