Second branch testing workflow with updations

diff --git a/.github/workflows/Test-kitctl.yml b/.github/workflows/Test-kitctl.yml
--- a/.github/workflows/Test-kitctl.yml
+++ b/.github/workflows/Test-kitctl.yml
@@ -102,21 +102,15 @@ jobs:
           export KUBECONFIG=/home/runner/.kit/env/kit-github-${{ github.run_id }}/etc/kubernetes/admin.conf
           kubectl get pods -A
           for i in {1..5}; do
-          if ./kitctl delete kit-github-${{ github.run_id }}; then
-              echo "Successfully deleted kit-github-${{ github.run_id }} on attempt $i"
-              break
-          else
-              echo "Attempt $i to delete kit-github-${{ github.run_id }} failed with exit code $?, retrying in $sleep_time seconds"
-          fi
+          ./kitctl delete kit-github-${{ github.run_id }}
           if [ $i -eq 1 ]; then
-              sleep_time=220
+              sleep 220
           else
-              sleep_time=60
+              sleep 60
           fi
-          sleep $sleep_time
           done
           if [ $i -eq 5 ]; then
-              echo "Failed to delete the kit-github-${{ github.run_id }} environment after 5 attempts. Please check the logs and manually delete the environment."
-              exit 1
+            echo "Failed to delete the kit-github-${{ github.run_id }} environment after 5 attempts. Please manually delete the environment."
+            exit 1
           fi
         working-directory: substrate
