Second branch testing workflow with updations

diff --git a/.github/workflows/Test-kitctl.yml b/.github/workflows/Test-kitctl.yml
--- a/.github/workflows/Test-kitctl.yml
+++ b/.github/workflows/Test-kitctl.yml
@@ -42,22 +42,26 @@ jobs:
           sudo mv kubectl /usr/local/bin/
       - name: Builds the KIT CLI ,Provisions the Kit Environment and deletes it
         run: |
-          pwd
-          ls -lta
           cd /Users/runner/work/kubernetes-iteration-toolkit/kubernetes-iteration-toolkit/substrate/cmd/kitctl
           GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v .
           ./kitctl bootstrap kit-github-${{ github.run_id }}
+          sleep 10
           export KUBECONFIG=/Users/runner/.kit/env/kit-github-${{ github.run_id }}/etc/kubernetes/admin.conf
+          sleep 10
           kubectl get pods -A
           for i in {1..5}; do
-          if ./kitctl delete kit-github-${{ github.run_id }}; then
-            break
+           if ./kitctl delete kit-github-${{ github.run_id }}; then
+           break
           fi
-          sleep 20
+          if [ $i -eq 1 ]; then
+              sleep 120
+          else
+              sleep 30
+          fi
           done
           if [ $i -eq 5 ]; then
-            echo "Failed to delete the kit-github-${{ github.run_id }} environment after 5 attempts. Please manually delete the environment."
-            exit 1
+              echo "Failed to delete the kit-github-${{ github.run_id }} environment after 5 attempts. Please manually delete the environment."
+              exit 1
           fi
         working-directory: substrate
   build-cli-linux:
@@ -93,23 +97,23 @@ jobs:
           sudo mv kubectl /usr/local/bin/  
       - name: Builds the KIT CLI ,Provisions the Kit Environment and deletes it
         run: |
-          pwd
           cd /home/runner/work/kubernetes-iteration-toolkit/kubernetes-iteration-toolkit/substrate/cmd/kitctl
           GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v .
           ./kitctl bootstrap kit-github-${{ github.run_id }}
-          sleep 10
           export KUBECONFIG=/home/runner/.kit/env/kit-github-${{ github.run_id }}/etc/kubernetes/admin.conf
-          sleep 10
           kubectl get pods -A
-          sleep 10
           for i in {1..5}; do
           if ./kitctl delete kit-github-${{ github.run_id }}; then
-            break
+           break
           fi
-          sleep 20
+          if [ $i -eq 1 ]; then
+              sleep 120
+          else
+              sleep 30
+          fi
           done
           if [ $i -eq 5 ]; then
-            echo "Failed to delete the kit-github-${{ github.run_id }} environment after 5 attempts. Please manually delete the environment."
-            exit 1
+              echo "Failed to delete the kit-github-${{ github.run_id }} environment after 5 attempts. Please manually delete the environment."
+              exit 1
           fi
         working-directory: substrate
